### ISSUE TITLE
No Daily Sensor - Configuration

### ISSUE THREAD

**Issue by zibous** [jeroenterheerdt/HADailySensor#1]
As described, I installed HADailySensor via HACS and restarted HA.

![Bildschirmfoto 2020-06-20 um 17 08 30](https://user-images.githubusercontent.com/30198737/85205030-c0981200-b318-11ea-9f10-d5565b84e529.png)

> Install the custom component (preferably using HACS) and then use the Configuration --> Integrations pane to search for 'Daily Sensor'.

But when I go to Configuration -> Integrations pane, I don't see the Daily Sensor and cannot configure one.

```txt
arch | x86_64
-- | --
dev | false
docker | false
hassio | false
installation_type | Home Assistant Core
os_name | Linux
os_version | 5.4.0-37-generic
python_version | 3.8.2
timezone | Europe/Vaduz
version | 0.111.4
virtualenv | true
Frontend-Version: 20200603.3 - latest
```

What can I do ?

**Comment by jeroenterheerdt** [comment]
Hmm, did the daily custom component get added to the folder?

**Comment by zibous** [comment]
Yes:

![Bildschirmfoto 2020-06-20 um 17 35 34](https://user-images.githubusercontent.com/30198737/85205658-02c35280-b31d-11ea-912f-27e92042d9fb.png)

try to set the sensor with yaml:

```yaml
- platform: daily
  name: 'Verbrauch Haus'
  sensor: sensor.verbrauch_gesamt
  operation: sum
  unit_of_measurement: 'Wh'

- platform: daily
  name: 'Ertrag Photovoltaik'
  sensor: sensor.kostal_current_watt
  operation: sum
  unit_of_measurement: 'Wh'
```

But i got his error message:
![Bildschirmfoto 2020-06-20 um 17 38 38](https://user-images.githubusercontent.com/30198737/85205671-12429b80-b31d-11ea-918f-4054ac1eae52.png)
